FROM rustlang/rust:nightly-bookworm

RUN apt-get update && apt-get install -y protobuf-compiler && rm -rf /var/lib/apt/lists/*

WORKDIR /app
COPY . .

RUN cargo build --release --tests

CMD ["cargo", "test", "--release", "--", "--nocapture"]
